#!/bin/bash

set -e

[ -z $UID ] || SUDO=sudo

# generate config file
$SUDO ${TKDIR}/genconf/nginx.pl

# Use the generated config
$SUDO /usr/sbin/nginx -c ${TKDIR}/run/nginx.conf  || exit 1
echo "* Nginx started with pid $(cat run/nginx.pid)!"
