#!/bin/bash
. /opt/telekinesis/lib/config.sh

RADIO=radio0

get_val ".radios.${RADIO}.cat_device"
CAT_DEV=$CF_VAL

get_val ".radios.${RADIO}.cat_baud"
CAT_BAUD=$CF_VAL

get_val ".radios.${RADIO}.rigctld_model"
RIG_MODEL=$CF_VAL

get_val ".radios.${RADIO}.rigctld_port"
RIG_PORT=$CF_VAL

# Start rigctld and save it's pid
rigctld -m ${RIG_MODEL} -s ${CAT_BAUD} -P RIG -t ${RIG_PORT} -r ${CAT_DEV} &
PID=$?
echo ${PID} > /opt/telekinesis/run/rigctld.${RADIO}.pid
