#!/bin/bash
. /opt/telekinesis/lib/config.sh
set -e
RADIO="radio0"

while true; do
   echo "[$(date +%Y-%m-%d.%H%M%S)] (re)starting..." >> ${TKDIR}/logs/telekinesis-ari.${RADIO}.log
   ${TKDIR}/ari-bin/tk-ari-legacy.pl ${RADIO}
   sleep 15
done
