#!/bin/bash
. /opt/telekinesis/lib/config.sh

RADIO="radio0"

while true; do
   echo "[$(date +%Y-%m-%d.%H%M%S)] (re)starting..." >> /opt/telekinesis/logs/telekinesis-ari.${RADIO}.log
   /opt/telekinesis/ari-bin/telekinesis-ssb-ari.pl ${RADIO}
   sleep 15
done
